import commit
from datetime import date


def updateTable(fileName, tasks):
    #search text until '^' character is found (find table)
    with open(fileName, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    
    place = 0
    for i in range(len(lines)):
        if lines[i].startswith('^'):
            place = i
            break

    #have found line, now need to write next set of lines
    place += 1 #moving forward to ignore table header
    lines = lines[0:place]
    for key in tasks:
        text = tasks[key].tablify() + "\n"
        lines.append(text)

    today = date.today()
    lines.append("\nThis wiki page has been auto generated by Nicholas Biancolin's Wiki Updater program | (c) 2024 Nicholas Biancolin - All Rights Reserved.\n \\\\")
    lines.append("Last updated: " + today.strftime('%y/%m/%d/%H/%M'))

    with open(fileName, 'w', encoding='utf-8') as file:
        file.writelines(lines)
    
    return lines


def readTable(fileName):
    with open(fileName, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    res = ""
    for elem in lines:
        res += elem
        res += "\n"

    return res